project:
    name: desafio-tecnico-maxinutri
    version: 1.0.0
    description: Projeto de ETL para o desafio técnico da Maxinutri
    authors:
        - name: Sisnando Junior
        - email: nando.devs@gmail.com
    license: MIT
    repository:
        type: git
<<<<<<< HEAD
        url: "https://github.com/nandodevs/case-tecnico-maxinutri"
=======
        url: "https://github.com/nandodevs/desafio-tecnico-maxinutri"
>>>>>>> 8ef029d9c58e300164d0708fa1707f9c196cc777
    keywords:
        - etl
        - airflow
        - postgres
        - python
<<<<<<< HEAD
        - docker
=======
>>>>>>> 8ef029d9c58e300164d0708fa1707f9c196cc777
    scripts:
        - etl/extract.py
        - etl/transform.py
        - etl/load.py
    dependencies:
        python: ">=3.8"
        pandas: "^2.0.3"
        requests: "^2.31.0"
        psycopg2-binary: "^2.9.6"
        apache-airflow: "^2.10.3"
        apache-airflow-providers-postgres: "^5.1.0"
    dev-dependencies:
        black: "^23.9.1"
        isort: "^5.12.0"
        flake8: "^6.1.0"
        mypy: "^1.4.1"
        pytest: "^7.4.0"
        pytest-cov: "^4.1.0"
        tox: "^4.12.1"



    

