# Configurações do Airflow

# Conexões do banco de dados
connections:
  - conn_id: postgres_default
    conn_type: postgres
    description: "Conexão para o banco 'desafiodb'"
    host: localhost
    port: 5544
    schema: desafiodb
    login: admin
    password: admin@123
    extra: 
      {
        "connect_timeout": 30,
        "application_name": "airflow_etl"
      }

  # - conn_id: postgres_creation
  #   conn_type: postgres
  #   description: "Conexão para criar o banco de dados"
  #   host: localhost
  #   port: 5432
  #   schema: postgres
  #   login: postgres
  #   password: postgres
    
# Variáveis do Airflow
variables:
  - key: api_url
    value: "${API_URL}"
    description: "URL da API de dados"
    
  - key: api_token
    value: "${TOKEN}" 
    description: "Token de autenticação da API"
    
  - key: max_retries
    value: "5"
    description: "Máximo de tentativas para requisições"
    
  - key: email_alerts
    value: "true"
    description: "Ativar alertas por email"

# Pools (opcional)
pools:
  - pool_name: etl_pool
    pool_slots: 2
    pool_description: "Pool para tasks ETL"