# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: postgres-default
      conn_type: postgres
      conn_host: host.docker.internal
      conn_schema: desafio_db 
      conn_login: postgres
      conn_password: admin123
      conn_port: 5545
      conn_description: Local Postgres DB
      conn_extra:
        sslmode: disable
        connect_timeout: 50
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value:
  networks:
    - network_name: airflow-network
      driver: bridge
   
