# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
  # - conn_id: meu_postgres
  #   conn_type: postgres
  #   description: "Conexão para o banco 'airflow_db' no PostgreSQL"
  #   host: localhost
  #   port: 5544
  #   schema: desafio_db
  #   login: airflow
  #   password: airflow123
  #   extra: "{\"connect_timeout\": 30, \"application_name\": \"airflow_etl\"}"
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value:
