<<<<<<< HEAD
version: '3.8'

networks:
  airflow_network:
    driver: bridge
    name: airflow_network
=======
version: '3.8'

networks:
  airflow_network:
    driver: bridge
    name: airflow_network
>>>>>>> 8ef029d9c58e300164d0708fa1707f9c196cc777
  